export default {
  email: "Email",
  confidence: "Confidence",
  indexed: "Date",
  defaultPositionWebsiteUrl: "Company URL",
  flagshipProfileUrl: "Profile URL",
  firstName: "First Name",
  lastName: "Last Name",
  fullName: "Full Name",
  "defaultPosition.location": "Location",
  "defaultPosition.title": "Job Title",
  "defaultPosition.companyName": "Company Name",
  industry: "Industry",
  location: "Company Location",
  // "contactInfo": "Public Contact Info",
  // "contactInfo.socialHandles": "Social Media",
  "contactInfo.socialHandles.name": "Social Handle",
  "contactInfo.socialHandles.type": "Social Network",
  "contactInfo.websites": "Websites",
  "defaultPosition.new": "New Job (90 Days)",
  "defaultPosition.current": "Current Position",
  "defaultPosition.description": "Job Description",
  "defaultPosition.startedOn.month": "Month Started",
  "defaultPosition.startedOn.year": "Year Started",
  headline: "Profile Headline",
  summary: "Profile Summary",
  "educations.schoolName": "School",
  "educations.degree": "Degree",
  "educations.startedOn.year": "Education Start",
  "educations.endedOn.year": "Education End",
  "educations.fieldsOfStudy": "Field of Study",
  numOfSharedConnections: "Shared Connections",
  degree: "Degree of Connection",
  numOfConnections: "Shared Connections",
};

// export default [
//     // `defaultPosition`,
//     `defaultPosition.companyName`,
//     `defaultPosition.title`,
//     // `defaultPosition.companyUrn`,
//     // `defaultPosition.posId`,
//     `defaultPosition.current`,
//     `defaultPosition.location`,
//     `defaultPosition.startedOn.month`,
//     `defaultPosition.startedOn.year`,
//     // `noteCount`,
//     `degree`,
//     `firstName`,
//     // `memberBadges`,
//     // `memberBadges.premium`,
//     // `memberBadges.openLink`,
//     // `memberBadges.jobSeeker`,
//     `lastName`,
//     `industry`,
//     // `entityUrn`,
//     `numOfConnections`,
//     // `profilePictureDisplayImage`,
//     // `profilePictureDisplayImage.artifacts`,
//     // `profilePictureDisplayImage.rootUrl`,
//     `headline`,
//     `profileUnlockInfo`,
//     // `profileUnlockInfo.showProfileUnlock`,
//     // `pendingInvitation`,
//     `fullName`,
//     // `pictureInfo`,
//     // `listCount`,
//     `flagshipProfileUrl`,
//     `location`,
//     `indexed`,
//     // `contactInfo`,
//     `contactInfo.websites`,
//     // `contactInfo.socialHandles`,
//     `contactInfo.socialHandles.name`,
//     `contactInfo.socialHandles.type`,
//     `defaultPosition.description`,
//     `summary`,
//     `numOfSharedConnections`,
//     // `contactInfo.emails`,
//     // `contactInfo.primaryEmail`
// ];
