name: Deploy to Cloudflare Pages

on:
  push:
  pull_request:

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"  

      - name: Yarn Install
        run: yarn install
      
      - name: Wrangler Install
        run: npm install -g wrangler

      - name: Create a Cloudflare Pages Project
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          projectName = $(echo $REPOSITORY | sed 's/\//-/g'})
          wrangler pages project list > wrangler_project_list.txt
          if grep -q "$projectName" wrangler_project_list.txt; then
            echo "Pages project already exists."
          else
            echo "Creating a Pages project."
          fi