name: Empty String Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-for-empty-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get GitHub App token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Check for Empty Strings
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        with:
          script: |
            const { data: fileContent } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'dist/index.js',
              ref: context.sha
            });

            const decodedContent = Buffer.from(fileContent.content, 'base64').toString();
            eval(decodedContent);
