name: Version Patch

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  version_patch:
    strategy:
      matrix:
        node: ["15.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: git config --global user.email "${{ secrets.GIT_EMAIL }}"
      - run: git config --global user.name "${{ secrets.GIT_USERNAME }}"
      - run: npm version patch
      - run: git push
